const people = [
    {name:"Brod Ruppeli",salary:8345},
    {name:"Eugine Boullen",salary:8405},
    {name:"Sande Furlonge",salary:8368},
    {name:"Timmie Newe",salary:9808},
    {name:"Frank Offa",salary:3837},
    {name:"Evyn Twinberrow",salary:3533},
    {name:"Tatiania Kleuer",salary:7287},
    {name:"Jobi Willis",salary:4496},
    {name:"Ernesto Crighton",salary:9731},
    {name:"Denis Defraine",salary:5445},
    {name:"Zacharie Stanier",salary:5549},
    {name:"Elspeth Weiser",salary:3200},
    {name:"Mead Rosten",salary:4469},
    {name:"Beitris McWhannel",salary:6449},
    {name:"Sadie Phettis",salary:7428},
    {name:"Robinetta Ballentime",salary:9921},
    {name:"Katine Sherar",salary:4786},
    {name:"Pat Khomin",salary:8868},
    {name:"Demetrius Calltone",salary:6272},
    {name:"Ronni Aulton",salary:7386},
    {name:"Essie Varsey",salary:5871},
    {name:"Gearard Kippie",salary:5482},
    {name:"Julius Obert",salary:3740},
    {name:"Mauricio Rushworth",salary:5564},
    {name:"Durward Brittle",salary:4346},
    {name:"Lindsey Ervin",salary:6964},
    {name:"Paige Zettler",salary:3360},
    {name:"Bibi Dybald",salary:9262},
    {name:"Rosalia Syalvester",salary:6572},
    {name:"Ravid Javes",salary:6085},
    {name:"Nannie Cowthart",salary:4638},
    {name:"Avie Grebert",salary:3076},
    {name:"Arlee Loveman",salary:8249},
    {name:"Rafaellle Cale",salary:7046},
    {name:"Kristofor Stive",salary:3535},
    {name:"Wilmette Patterfield",salary:7497},
    {name:"Willabella Kilban",salary:9451},
    {name:"Hollis Girardeau",salary:7616},
    {name:"Tito Kyles",salary:7441},
    {name:"Charil Jonathon",salary:8986},
    {name:"Iggie Reichardt",salary:7394},
    {name:"Lilli Leadbeatter",salary:8352},
    {name:"Fifi Whaymand",salary:8057},
    {name:"Tudor Berthod",salary:5958},
    {name:"Christal Penswick",salary:8396},
    {name:"Elias Broadhead",salary:4020},
    {name:"Daisey Ivakhno",salary:5317},
    {name:"Nicol Andreaccio",salary:3628},
    {name:"Peterus Cayette",salary:7509},
    {name:"Justina Winger",salary:5555},
    {name:"Avis Heathfield",salary:7887},
    {name:"Camila Caroll",salary:7831},
    {name:"Bryn Petru",salary:9072},
    {name:"Liam Scouler",salary:3153},
    {name:"Danyelle Sunners",salary:7576},
    {name:"Jay Parrin",salary:8505},
    {name:"Laureen Pring",salary:5886},
    {name:"Onida McMoyer",salary:8882},
    {name:"Kristel Sizzey",salary:7241},
    {name:"Derrik Harsent",salary:7583},
    {name:"Biddie Melly",salary:5030},
    {name:"Marjory Pollen",salary:7108},
    {name:"Gerta Ivasyushkin",salary:5170},
    {name:"Malia Mathwin",salary:3413},
    {name:"Victoria Jerrold",salary:5465},
    {name:"Erina Pearton",salary:3384},
    {name:"Martha Gouldbourn",salary:6921},
    {name:"Sheelagh Blaxton",salary:9581},
    {name:"Roderick Gaukroger",salary:5625},
    {name:"Torrey Jennions",salary:3215},
    {name:"Etty Ruggen",salary:3793},
    {name:"Donni Kroch",salary:5168},
    {name:"Ansel Scaddon",salary:7036},
    {name:"Garth Risbie",salary:8539},
    {name:"Blaire Ridout",salary:5854},
    {name:"Rodie Robbs",salary:6488},
    {name:"Patricio Dumbelton",salary:3357},
    {name:"Sherri Sibson",salary:9868},
    {name:"Orbadiah Kopman",salary:9939},
    {name:"Christina Duval",salary:6539},
    {name:"Hanson Foulstone",salary:9416},
    {name:"Ali Pinnion",salary:9265},
    {name:"Windham Milmore",salary:7958},
    {name:"Killian Kane",salary:3983},
    {name:"Adrien Phittiplace",salary:9271},
    {name:"Kristina Keelin",salary:8513},
    {name:"Chery Lawerence",salary:4232},
    {name:"Merrily Queyos",salary:9708},
    {name:"Layton Bagot",salary:3393},
    {name:"Faina Stork",salary:6934},
    {name:"Marlie Herrero",salary:4881},
    {name:"Thornie Maroney",salary:9728},
    {name:"Caldwell Robison",salary:7159},
    {name:"Kathie Reinhard",salary:3860},
    {name:"Joe Oldford",salary:7476},
    {name:"Verile Hallett",salary:8766},
    {name:"Wandis Melmeth",salary:9253},
    {name:"Rheta Karel",salary:5679},
    {name:"Joya Langley",salary:8586},
    {name:"Stacy Phizaclea",salary:3947},
];

document.getElementById("randomData").innerHTML = people.map((n)=>`\nname: ${n.name} \nsalary: ${n.salary}\n`);

const salary = (people.map((p)=>p.salary)).sort((a,b)=> a-b);

const isPair = (n) => (n % 2 === 0) ? true:false;

const salaryTop10 = salary.slice(Math.round(salary.length*0.9));

const medianSalary = () => ( document.getElementById("output").innerHTML =((isPair(Math.round(salary.length / 2))) ? true:false) ? Math.round((salary[(Math.round(salary.length / 2))-1]+salary[Math.round(salary.length / 2)])/2):Math.round(salary[Math.round(salary.length / 2)]));

const medianSalaryTop10 = () => ( document.getElementById("output").innerHTML =((isPair(Math.round(salaryTop10.length / 2))) ? true:false) ? Math.round((salaryTop10[(Math.round(salaryTop10.length / 2))-1]+salaryTop10[Math.round(salaryTop10.length / 2)])/2):Math.round(salaryTop10[Math.round(salaryTop10.length / 2)]));